<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.noos.xing</groupId>
        <artifactId>mydoggy-builder</artifactId>
        <version>1.5.1</version>
    </parent>
    <artifactId>mydoggy-res</artifactId>
    <name>mydoggy-res</name>
    <version>1.5.1</version>
    <url>http://mydoggy.sourceforge.net</url>
    <description>MyDoggy - My Java Docking Framework - Plaf Resources:
        MyDoggy-Res contains resources for mydoggy plaf.
    </description>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>

