/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.novatronic.formatter.gui.panels;

import com.novatronic.formatter.gui.Components;
import com.novatronic.formatter.gui.ComponentsID;

/**
 *
 * @author Omar
 */
public class IFAndFrameTestPanel extends javax.swing.JPanel {

    /**
     * Creates new form IFAndFrameTestPanel
     */
    public IFAndFrameTestPanel() {
        initComponents();
        addComponents();
    }
    
    private void addComponents(){
        Components CompManager = Components.getInstance();
        CompManager.add(jbLoadFmtCfg, ComponentsID.BT_LOAD_FMTCFG);
        CompManager.add(jbLoadFmtIds, ComponentsID.BT_LOAD_FMTIDS);
        CompManager.add(jbFmtLogToXml, ComponentsID.BT_FMTLOG_TO_XML);
        CompManager.add(jbXmlToFrame, ComponentsID.BT_XML_TO_FRAME);
        CompManager.add(jbFrameToXmlAndLog, ComponentsID.BT_FRAME_TO_XMLANDLOG);
        CompManager.add(jtaFrame, ComponentsID.TA_FRAME);
        CompManager.add(jtaFmtLog, ComponentsID.TA_FMTLOG);
        CompManager.add(jtaFmtXml, ComponentsID.TA_FMTXML);
        CompManager.add(jcFmtCfg, ComponentsID.CB_FMTCFG);
        CompManager.add(jcFmtId, ComponentsID.CB_FMTID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcFmtCfg = new javax.swing.JComboBox();
        jbLoadFmtCfg = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jcFmtId = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaFrame = new javax.swing.JTextArea();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaFmtXml = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaFmtLog = new javax.swing.JTextArea();
        jbXmlToFrame = new javax.swing.JButton();
        jbFrameToXmlAndLog = new javax.swing.JButton();
        jbFmtLogToXml = new javax.swing.JButton();
        jbLoadFmtIds = new javax.swing.JButton();

        jLabel1.setText("Archivo de Configuración:");

        jbLoadFmtCfg.setPreferredSize(new java.awt.Dimension(70, 25));

        jLabel2.setText("Formato:");

        jSplitPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setDividerSize(10);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.56);
        jSplitPane1.setOneTouchExpandable(true);

        jtaFrame.setColumns(20);
        jtaFrame.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jtaFrame.setLineWrap(true);
        jtaFrame.setRows(5);
        jScrollPane1.setViewportView(jtaFrame);

        jSplitPane1.setBottomComponent(jScrollPane1);

        jSplitPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSplitPane2.setDividerLocation(350);
        jSplitPane2.setDividerSize(10);
        jSplitPane2.setResizeWeight(0.56);
        jSplitPane2.setOneTouchExpandable(true);

        jtaFmtXml.setColumns(20);
        jtaFmtXml.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jtaFmtXml.setRows(5);
        jScrollPane2.setViewportView(jtaFmtXml);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(jPanel2);

        jtaFmtLog.setColumns(20);
        jtaFmtLog.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jtaFmtLog.setRows(5);
        jScrollPane3.setViewportView(jtaFmtLog);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );

        jSplitPane2.setLeftComponent(jPanel3);

        jSplitPane1.setLeftComponent(jSplitPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );

        jbXmlToFrame.setPreferredSize(new java.awt.Dimension(19, 25));

        jbFrameToXmlAndLog.setPreferredSize(new java.awt.Dimension(33, 25));

        jbFmtLogToXml.setPreferredSize(new java.awt.Dimension(19, 25));

        jbLoadFmtIds.setPreferredSize(new java.awt.Dimension(70, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcFmtCfg, 0, 161, Short.MAX_VALUE)
                    .addComponent(jcFmtId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbLoadFmtCfg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLoadFmtIds, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbFmtLogToXml, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbXmlToFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbFrameToXmlAndLog, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jcFmtCfg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLoadFmtCfg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbFmtLogToXml, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbXmlToFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jcFmtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbFrameToXmlAndLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLoadFmtIds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JButton jbFmtLogToXml;
    private javax.swing.JButton jbFrameToXmlAndLog;
    private javax.swing.JButton jbLoadFmtCfg;
    private javax.swing.JButton jbLoadFmtIds;
    private javax.swing.JButton jbXmlToFrame;
    private javax.swing.JComboBox jcFmtCfg;
    private javax.swing.JComboBox jcFmtId;
    private javax.swing.JTextArea jtaFmtLog;
    private javax.swing.JTextArea jtaFmtXml;
    private javax.swing.JTextArea jtaFrame;
    // End of variables declaration//GEN-END:variables
}
