/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.novatronic.formatter.gui.panels;

import com.novatronic.formatter.gui.ComponentsID;
import com.novatronic.formatter.gui.Components;

/**
 *
 * @author Omar
 */
public class LogPanel extends javax.swing.JPanel {

    /**
     * Creates new form Log
     */
    public LogPanel() {
        initComponents();
        addComponents();
    }
    
    private void addComponents(){
        Components CompManager = Components.getInstance();
        CompManager.add(txaLog, ComponentsID.TA_TEST_LOG);
        CompManager.add(miCleanLog, ComponentsID.MI_CLEAN_TEST_LOG);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        miCleanLog = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaLog = new javax.swing.JTextArea();

        miCleanLog.setText("Limpiar Log");
        jPopupMenu1.add(miCleanLog);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txaLog.setColumns(20);
        txaLog.setEditable(false);
        txaLog.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        txaLog.setLineWrap(true);
        txaLog.setRows(5);
        txaLog.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(txaLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem miCleanLog;
    private javax.swing.JTextArea txaLog;
    // End of variables declaration//GEN-END:variables
}
