version: '3.8'

services:
  pgwp-orchestrator:
    image: pgwp-orchestrator:latest
    networks:
      - internal-pe
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          cpus: '250m'
          memory: '500M'
        reservations:
          cpus: '250m'
          memory: '200M'
    environment:
      - ATENEA_MRID=mr_pe
      - ATENEA_NAMESPACE=gateway.payauth.pe
      - ATENEA_UUAA=PGWP
      - ATENEA_SERVICE=pgwp-orchestrator
      - ATENEA_ENVIRONMENT=PAAS
      - NETWORK=PEER02
      - PORT=9097
      - GRPC_SERVER_ADDRESS=0.0.0.0
      - GRPC_SERVER_PORT=9097
      - ORCHESTRATION_FLOWHANDLER_ADDRESS=pgwp-flowhandler
      - ORCHESTRATION_FLOWHANDLER_PORT=9092
      - ORCHESTRATION_MONITOR_ADDRESS=pgwp-monitor
      - ORCHESTRATION_MONITOR_PORT=9096
      - ORCHESTRATION_FRAUD_ADDRESS=pgwp-fraud
      - ORCHESTRATION_FRAUD_PORT=9095
      - ORCHESTRATION_CRYPTO_ADDRESS=pgwp-crypto
      - ORCHESTRATION_CRYPTO_PORT=9094
      - ORCHESTRATION_APICONNECTOR_ADDRESS=pgwp-apiconnector
      - ORCHESTRATION_APICONNECTOR_PORT=9093
      - ORCHESTRATION_EVENTS_ADDRESS=kgwy-events
      - ORCHESTRATION_EVENTS_PORT=9091
      - ORCHESTRATION_DIALOG_ADDRESS=pgwp-dialog
      - ORCHESTRATION_DIALOG_PORT=9098
      - ORCHESTRATION_PROXYPROCESSOR_ADDRESS_7003=pgwp-proxyprocessor-peer02-6034
      - ORCHESTRATION_PROXYPROCESSOR_PORT_7003=9240
      - ORCHESTRATION_PROXYHOST_ADDRESS_7003=pgwp-proxyhost-peer02-6034
      - ORCHESTRATION_PROXYHOST_PORT_7003=9260
      - ORCHESTRATION_PROXYPROCESSOR_ADDRESS_1234=pgwp-proxyprocessor-peer01-1234
      - ORCHESTRATION_PROXYPROCESSOR_ADDRESS_1235=pgwp-proxyprocessor-peer01-1235
      - ORCHESTRATION_PROXYPROCESSOR_PORT_1234=9200
      - ORCHESTRATION_PROXYPROCESSOR_PORT_1235=9200
      - ORCHESTRATION_PROXYHOST_ADDRESS_1234=pgwp-proxyhost-peer01-1234
      - ORCHESTRATION_PROXYHOST_ADDRESS_1235=pgwp-proxyhost-peer01-1235
      - ORCHESTRATION_PROXYHOST_PORT_1234=9220
      - ORCHESTRATION_PROXYHOST_PORT_1235=9220
      - ORCHESTRATION_PROXY_GRPC_CLIENT_KEEP_ALIVE_TIME=1200
      - ORCHESTRATION_PROXY_GRPC_CLIENT_KEEP_ALIVE_TIMEOUT=60
      - ORCHESTRATION_PROXY_GRPC_CLIENT_KEEP_ALIVE_WITHOUT_CALLS=TRUE
      - ORCHESTRATION_DUMMYPROCESSOR_ADDRESS=pgwp-dummyprocessor
      - ORCHESTRATION_DUMMYPROCESSOR_PORT=9099
      - ORCHESTRATION_DUMMYPROCESSOR_GRPC_CLIENT_KEEP_ALIVE_TIME=1200
      - ORCHESTRATION_DUMMYPROCESSOR_GRPC_CLIENT_KEEP_ALIVE_TIMEOUT=60
      - ORCHESTRATION_DUMMYPROCESSOR_GRPC_CLIENT_KEEP_ALIVE_WITHOUT_CALLS=TRUE

networks:
  internal-pe:
    driver: bridge