#Directorio donde se ubican los test
test.dir=tests

#Directorio donde se ubican los formatos
formats.dir=formatos

#Prefijo de los archivos de test
testfile.prefix=test

#Maquina de Estados del Panel de Pruebas
sm.test.panel=PanelStates.xml

#Configura los iconos y tooltip de la aplicacion
config.icons=Desing.xml

#Configura las acciones en la Interfaz
config.actions=Actions.xml